-- Create followers table
CREATE TABLE IF NOT EXISTS public.followers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    follower_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    following_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    UNIQUE(follower_id, following_id)
);

-- Create RLS policies
ALTER TABLE public.followers ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view followers" ON public.followers
    FOR SELECT USING (true);

CREATE POLICY "Users can manage their own following" ON public.followers
    FOR ALL USING (auth.uid() = follower_id);

-- Create indexes
CREATE INDEX followers_follower_id_idx ON public.followers(follower_id);
CREATE INDEX followers_following_id_idx ON public.followers(following_id);
